HomebrewFormula: Change `:lion` to `"10.7"`
I got this error recently:

    $ brew tap teddywing/formulae
    Updating Homebrew...
    ...
    ==> Tapping teddywing/formulae
    Cloning into '/usr/local/Homebrew/Library/Taps/teddywing/homebrew-formulae'...
    ...
    Error: Invalid formula: /usr/local/Homebrew/Library/Taps/teddywing/homebrew-formulae/HomebrewFormula/dome-key.rb
    dome-key: unknown version :lion
    Error: Cannot tap teddywing/formulae: invalid syntax in tap!

Turns out `:lion` was removed as a Mac OS X version symbol from
Homebrew:
https://github.com/homebrew/brew/commit/1aa8ad09e212cd9cd2f3ae55f899ed4ef03ae4d0

Use a version string instead.